import Nav from "@/component/Nav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Nav />
          <div className="flex-grow p-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
